defaults:
  - base
  - _self_  # Ensure dataset-specific configs override base

generate:
  lm_model: "gpt-4o-mini"
  output_length: 128
  num_of_examples: 144
  concept_path: "axbench/data/gemma-2-2b_10-gemmascope-res-16k.json"
  max_concepts: 500
  master_data_dir: "assets/data/axbench"
  dataset_category: "instruction"
  lm_use_cache: false
  seed: 42
train:
  model_name: "google/gemma-2-2b-it"
  layer: 10
  component: "res"
  seed: 42
  use_bf16: true
  models:
    LsReFT:
      batch_size: 6
      gradient_accumulation_steps: 1
      n_epochs: 3
      lr: 0.01
      weight_decay: 0.00
      topk: 8
      coeff_latent_l1_loss: 0.005
      low_rank_dimension: 1
      intervention_positions: "all"
      intervention_type: "addition" # clamping
      binarize_dataset: false
      train_on_negative: true
      exclude_bos: true
inference:
  use_bf16: true
  models: ["LsReFT"]
  model_name: "google/gemma-2-2b-it"
  # latent related params
  output_length: 128
  latent_num_of_examples: 36
  latent_batch_size: 32
  # steering related params
  steering_intervention_type: "addition" # clamping
  steering_model_name: "google/gemma-2-2b-it"
  steering_datasets: ["AlpacaEval"]
  steering_batch_size: 10
  steering_output_length: 128
  steering_layers: [10]
  steering_num_of_examples: 10 # number of examples per concept and per factor
  steering_factors: [1] # number of steering factors per example
  # master data dir is shared across all jobs.
  master_data_dir: "assets/data/axbench"
  data_dir: axbench/axbench/concept10/prod_2b_l10_v1/generate
  seed: 42
  lm_model: "gpt-4o-mini"
  # generation related params
  temperature: 1.0
evaluate:
  models: ["LsReFT"]
  latent_evaluators: ["AUCROCEvaluator", "HardNegativeEvaluator"]
  steering_evaluators: ["PerplexityEvaluator", "LMJudgeEvaluator"]
  winrate_split_ratio: 0.5 # this is for steering only, we use a separate partition for factor selection.
  # Number of processes to run in parallel for steering evaluation.
  num_of_workers: 32
  lm_model: "gpt-4o-mini"
  run_winrate: false
  winrate_baseline: "PromptSteering"
  # master data dir is shared across all jobs.
  master_data_dir: "assets/data/axbench"
