defaults:
  - base
  - _self_

subspace_module: "BatchLsReFT"
name_or_path: null
target_model_name_or_path: "google/gemma-2-2b-it"
intervention_layer: [20]
intervention_positions: "all"

use_lm_hypernetwork: false
interpretor_type: "steering"
concept_detection: true
reft_hypernetwork: "LsReFT"
top_k: 8
reconstruction_loss_weight: 1.0
sft_loss_weight: 1.0
topk_sparsity_weight: 5e-3
objective: "reconstruction"
# For position axis
weight_sharing: true