defaults:
  - base
  - _self_

name_or_path: "TinyLlama/TinyLlama_v1.1"
target_model_name_or_path: "google/gemma-2b"
das_dimension: 32
num_editing_heads: 32
num_decoders: 8
target_hidden_size: 2048
chop_editor_at_layer: 15  # Make sure it's also here
intepretor_type: "learned_source"