# version: '3.8'
services:
  hyperdas:
    restart: always
    container_name: hyperdas
    image: ghcr.io/sidnb13/hyperdas:latest
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        GIT_EMAIL: ${GIT_EMAIL}
        GIT_NAME: ${GIT_NAME}
    volumes:
      - ./assets:/workspace/HyperDAS/assets
      - ~/.cache/huggingface/:~/.cache/huggingface/
      - ./.vscode-server:/.vscode-server # volume of the vscode plugins
      - ~/.ssh/id_ed25519:/root/.ssh/id_ed25519:ro # volume of the ssh keys
    # set environment variables
    env_file: .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: tail -f /dev/null
    ipc: host
