services:
  hyperdas:
    restart: always
    container_name: hyperdas
    image: ghcr.io/${GITHUB_USERNAME}/hyperdas:latest
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        GIT_EMAIL: ${GIT_EMAIL}
        GIT_NAME: ${GIT_NAME}
    volumes:
      - .:/workspace/HyperDAS
      - ./assets:/workspace/HyperDAS/assets
      - ${HOME}/.cache/huggingface:/root/.cache/huggingface
      - ./.vscode-server:/.vscode-server
      - ${HOME}/.ssh/id_ed25519:/root/.ssh/id_ed25519:ro
    ports:
      - "8765:8265" # Changed from 8266:8265
      - "10001:10001"
      - "6379:6379"
    command: >
      bash -c "
      ray start --head
      --include-dashboard=true
      --dashboard-host=0.0.0.0
      --dashboard-port=8265
      --port=6379
      --ray-client-server-port=10001
      --node-ip-address=0.0.0.0
      --block &&
      tail -f /dev/null"
    env_file: .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ipc: host
