services:
  hyperdas:
    restart: always
    container_name: hyperdas
    image: ghcr.io/sidnb13/hyperdas:latest
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        GIT_EMAIL: ${GIT_EMAIL}
        GIT_NAME: ${GIT_NAME}
    volumes:
      - ./assets:/workspace/HyperDAS/assets
      - ~/.cache/huggingface/:~/.cache/huggingface/
      - ./.vscode-server:/.vscode-server
      - ~/.ssh/id_ed25519:/root/.ssh/id_ed25519:ro
    env_file: .env
    environment:
      - RAY_ADDRESS=ray://ray-head:10001
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: tail -f /dev/null
    ipc: host
    depends_on:
      - ray-head

  ray-head:
    image: rayproject/ray:latest
    ports:
      - "8265:8265" # Ray dashboard
      - "10001:10001" # Ray client server port
    command: >
      ray start --head
      --port=6379
      --ray-client-server-port=10001
      --dashboard-host=0.0.0.0
      --dashboard-port=8265
      --block
    networks:
      - ray_network

networks:
  ray_network:
    driver: bridge
