services:
  hyperdas:
    restart: always
    container_name: hyperdas
    image: ghcr.io/sidnb13/hyperdas:latest
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        GIT_EMAIL: ${GIT_EMAIL}
        GIT_NAME: ${GIT_NAME}
    volumes:
      - ./assets:/workspace/HyperDAS/assets
      - ~/.cache/huggingface/:~/.cache/huggingface/
      - ./.vscode-server:/.vscode-server
      - ~/.ssh/id_ed25519:/root/.ssh/id_ed25519:ro
    env_file: .env
    environment:
      - RAY_HEAD_ADDRESS=ray-head:6379
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: tail -f /dev/null
    ipc: host
    depends_on:
      - ray-head

  ray-head:
    image: rayproject/ray:latest
    ports:
      - "8265:8265"  # Ray dashboard
      - "6379:6379"  # Ray head port
    command: >
      ray start --head
      --port=6379
      --dashboard-host=0.0.0.0
      --dashboard-port=8265
      --block