resources:
  cloud: lambda
  image_id: ghcr.io/${GIT_NAME}/hyperdas:latest

setup: |
  git config --global url."https://${GITHUB_TOKEN}:x-oauth-basic@github.com/".insteadOf "git://github.com/"
  git config --global url."ssh://git@github.com/".pushInsteadOf "https://github.com/"

run: |
  source deactivate
  nvidia-smi


envs:
  # Values used in: docker login -u <user> -p <password> <registry server>
  SKYPILOT_DOCKER_USERNAME: ${GIT_NAME}
  SKYPILOT_DOCKER_PASSWORD: ${GITHUB_TOKEN}
  SKYPILOT_DOCKER_SERVER: ghcr.io

  GITHUB_TOKEN: ${GITHUB_TOKEN}
