defaults:
  - _self_
  - model: llama3_8b
  - dataset: city
  - training: base
  - loss: base
  - wandb_config: base
  - experiment: null  # This should merge at root level
  - override hydra/launcher: parallel 
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

# Only keep other parameters here
load_trained_from: null
target_intervention_num: null
device_mode: null