defaults:
  - _self_
  - override hydra/launcher: joblib

# Common parameters
compute_metrics: false # whether to compute metrics for das modules and log
log_wandb: false
wandb_project: ${oc.env:WANDB_PROJECT,"HyperDAS"}
wandb_run_name: ${oc.env:WANDB_RUN_NAME,"${subspace_module}_${now:%Y%m%d_%H%M%S}"}
wandb_group: ${oc.env:WANDB_GROUP,null}
wandb_tags: ${oc.env:WANDB_TAGS,null}
wandb_notes: ${oc.env:WANDB_NOTES,null}
intervention_layer: 15
load_trained_from: null
n_epochs: 5
n_steps: -1
model_name_or_path: "/nlp/scr/sjd24/llama3-8b"
train_batch_size: 16
test_batch_size: 64
save_dir: null
test_path: "./experiments/RAVEL/data/city_test"
train_path: "./experiments/RAVEL/data/city_train"
causal_loss_weight: 1.0
das_dimension: 128
lr: 1e-4
eval_per_steps: 100
checkpoint_per_steps: null
max_eval_steps: -1
num_workers: 4

# Specific parameters for train.py
source_suffix_visibility: false
base_suffix_visibility: false
source_selection_sparsity_loss: true
sparsity_loss_warm_up_ratio: 0.25
sparsity_loss_weight_start: 0.0
sparsity_loss_weight_end: 1.0
target_intervention_num: null
iso_loss_weight: 1.0
save_model: false
inference_modes:
  ["default", "bidding_argmax", "groundtruth", "column_argmax", "global_argmax"]
num_decoders: 8
initialize_from_scratch: false
ablate_base_token_attention: false
ablate_source_token_attention: false
break_asymmetric: false
subspace_module: "ReflectSelect"
weight_decay: 0.01
max_grad_norm: 4.0
debug_model: false

# ridge projective parameters
top_k_parameter: 128
lambda_parameter: 1
importance_power: -2
epsilon: 1e-6
# inv_alpha, topk_ste, sigmoid, softmax 
ridge_parameterization: "inv_alpha"

# Specific parameters for train_ablation.py
# (Add any specific parameters here)

# Specific parameters for train_baseline.py
intervention_location: "last_entity_token"

hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ./multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}

  launcher:
    _target_: hydra_plugins.hydra_joblib_launcher.joblib_launcher.JoblibLauncher
    n_jobs: -1  # Use all available cores
    backend: null
    prefer: processes
    require: null
    verbose: 0
    timeout: null
    pre_dispatch: 2*n_jobs
    batch_size: auto
    temp_folder: null
    max_nbytes: null
    mmap_mode: r