log: false
project: ${oc.env:WANDB_PROJECT,"HyperDAS"}
run_name: ${oc.env:WANDB_RUN_NAME,"${model.subspace_module}_${now:%Y%m%d_%H%M%S}"}
group: ${oc.env:WANDB_GROUP,null}
tags: ${oc.env:WANDB_TAGS,null}
notes: ${oc.env:WANDB_NOTES,null}