# Common dataset parameters
source_suffix_visibility: false
base_suffix_visibility: false
dataset_type: ravel # or axbench
train_ratio: 0.8
seed: 42

train_path: null
test_path: null
reconstruction_train_path: null
reconstruction_test_path: null
eval_path: null