defaults:
  - base
  - _self_  # Ensure dataset-specific configs override base

train_path: "experiments/RAVEL/gemma2_data/city_continent_train"
test_path: "experiments/RAVEL/gemma2_data/city_continent_test"
dataset_type: ravel