defaults:
  - base
  - _self_ # Ensure dataset-specific configs override base

train_path: "axbench/axbench/concept16k/prod_2b_l20_v1/generate/train_data.parquet"
# test_path: "axbench/axbench/concept500/prod_2b_l20_v1/generate/train_data.parquet"
reconstruction_train_path: "assets/data/axbench/prod_2b_l20_concept16k_lsreft/train"
# reconstruction_test_path: "assets/data/axbench/prod_2b_l20_concept500_lsreft/train"
dataset_type: axbench
axbench_mode: ["train_steering"]
split_by: concept
