defaults:
  - base
  - _self_ # Ensure dataset-specific configs override base

train_path: "experiments/axbench/concept10_2b_l10"
test_path: "experiments/axbench/concept10_2b_l10"
dataset_type: axbench
axbench_mode: steering
split_by: concept