defaults:
  - base
  - _self_  # Ensure dataset-specific configs override base

train_path: "experiments/RAVEL/data/nobel_prize_winner_train"
test_path: "experiments/RAVEL/data/nobel_prize_winner_test"