name: build-push-cuda-docker-image

on:
  push:
    branches: [main]
    paths:
      - "requirements*.txt"
      - "Dockerfile"
      - "docker-compose*.yml"
      - ".docker/**"
      - ".github/workflows/docker-build.yaml"
  pull_request:
    branches: [main]
    paths:
      - "requirements*.txt"
      - "Dockerfile"
      - "docker-compose*.yml"
      - ".docker/**"
      - ".github/workflows/docker-build.yaml"

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Load env file
        run: cat .env.public >> $GITHUB_ENV

      - name: Setup NVIDIA Container Toolkit
        run: |
          distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
          curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -
          curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list
          sudo apt-get update && sudo apt-get install -y nvidia-container-toolkit

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Create .env file
        run: |
          echo "GIT_EMAIL=${{ secrets.GIT_EMAIL }}" > .env
          echo "GIT_NAME=${{ github.actor }}" >> .env

      - name: Build and push with Docker Compose
        run: |
          docker compose build
          docker compose push
